name: golangci-lint
on: [push,  pull_request]

jobs:
  saga-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
          cache: yarn
          cache-dependency-path: ./rpgsaga/foxfox/yarn.lock
      - name: Lint Saga
        run: |
          cd ./rpgsaga/saga
          yarn install --immutable --immutable-cache --check-cache
          yarn run test
      - name: Test Saga
        run: |
          cd ./rpgsaga/saga
          yarn install --immutable --immutable-cache --check-cache
          yarn run test
        
         